#!/bin/sh

set -eux

# No point in running these when non-Rust related changes are made. README.md is included because
# we're using it as our crate's doc comment and it may contain examples.
if git diff --cached --quiet -- "*.rs" README.md Cargo.toml rustfmt.toml rust-toolchain.toml; then
    exit
fi

cargo fmt --all --check
cargo hack --feature-powerset clippy --all-targets --exclude-features default --group-features gizmos,DO_NOT_USE_internal_tests_disable_gizmos -- -D warnings
cargo test --all-features
